# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#
#docker pull jtandedocker/min-nbk:py-3.10.6-nbpuller
singleuser:
  # Defines the default image
  image:
    name: jtandedocker/min-nbk
    tag: py-3.10.6-nbpuller
  profileList:
    - display_name: "Minimal environment with python"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment (python,R, and Julia)"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jtandedocker/datascience-nbk:py-3.10.6-nbpuller
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jtandedocker/allspark-nbk:py-3.10.6-nbpuller
    - display_name: "Deeplearning with TensorFlow"
      description: "Datascience Environment with Sample Notebooks"
      kubespawner_override:
        image: jtandedocker/tensorflow-nbk:py-3.10.6-nbpuller
        lifecycleHooks:
          postStart:
            exec:
              command:
                [
                  "gitpuller",
                  "https://github.com/jtande/jhub-file-download",
                  "SampleNoteBooks",
                  "SampleNoteBooks", 
                ]
  # `cmd: null` allows the custom CMD of the Jupyter docker-stacks to be used
  # which performs further customization on startup.
  cmd: null
  #
  # JupyterLab as the default UI
  defaultUrl: "/lab"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    EDITOR: "vim"
#  lifecycle_hooks:
#    postStart:
#      exec:
#       command:
#         - "sh"
#         - "-c"
#         - >
#           gitpuller https://github.com/jtande/jhub-file-download SampleNoteBooks SampleNoteBooks;


