FROM jupyter/all-spark-notebook:python-3.10.6
# docker pull jupyter/all-spark-notebook:python-3.10.6
# Replace `latest` with an image tag from to ensure reproducible builds:
# https://hub.docker.com/r/jupyter/minimal-notebook/tags/
# Inspect the Dockerfile at:
# https://github.com/jupyter/docker-stacks/tree/HEAD/minimal-notebook/Dockerfile

# install additional package...
#RUN pip install --no-cache-dir astropy
RUN pip install nbgitpuller

# set the default command of the image,
# if you want to launch more complex startup than the default `juptyerhub-singleuser`.
# To launch an image's custom CMD instead of the default `jupyterhub-singleuser`
# set `singleuser.cmd: null` in your config.yaml.

##Customizing jupyterhub
# https://z2jh.jupyter.org/en/stable/jupyterhub/customizing/user-environment.html
## Customized conda environment
# https://discourse.jupyter.org/t/how-to-make-created-custom-conda-environments-persist-across-user-sessions-in-jupyter-hub-on-aws-eks-cluster/12111/5
## Repo information on how to set conda for individual user
# https://repo2docker.readthedocs.io/en/latest/config_files.html
## Installing repodock
# https://z2jh.jupyter.org/en/stable/repo2docker.html#r2d-custom-image

